== References

The following documents are referred to in the text in such a way that some or all of their content
constitutes requirements of this document.

* WMO: _Manual on Codes, Volume I.1, Part A – Alphanumeric Codes_. WMO-No. 306, World Meteorological Organization, Geneva.
* WMO: _Manual on Codes, Volume I.2, Part B – Binary Codes and Part C – Common Features to Binary and Alphanumeric Codes_. WMO-No. 306, World Meteorological Organization, Geneva.
* WMO: _Guidelines for the Submission of the World Weather Records 2011+_. WMO-No. 1186, World Meteorological Organization, Geneva.
* WMO: _WIGOS Metadata Standard_. WMO-No. 1192, World Meteorological Organization, Geneva.
* WMO: _WMO Guidelines on the Calculation of Climate Normals_. WMO-No. 1203, World Meteorological Organization, Geneva.
* WMO: _Manual on High-quality Global Data Management Framework for Climate_. WMO-No. 1238, World Meteorological Organization, Geneva.
* WMO: _Guidelines on Surface Station Data Quality Control and Quality Assurance for Climate Applications_. WMO-No. 1269, World Meteorological Organization, Geneva.
* S. Bradner, IETF RFC 2119: _Key words for use in RFCs to Indicate Requirement Levels_. RFC Publisher (1997). https://www.rfc-editor.org/rfc/rfc2119
* Y. Shafranovich, IETF RFC 4180: _Common Format and MIME Type for Comma-Separated Values (CSV) Files_. RFC Publisher (2005). https://www.rfc-editor.org/rfc/rfc4180
* L. Moreau and P. Missier (eds.): _PROV-DM: The PROV Data Model_. W3C Recommendation, 30 April 2013. https://www.w3.org/TR/prov-dm/
* T. Lebo, et al. (eds.): PROV-O: _The PROV Ontology. W3C Recommendation_, 30 April 2013. https://www.w3.org/TR/prov-o/
* _NetCDF Climate and Forecast (CF) Metadata Conventions_. https://cfconventions.org/
* OGC: OGC 15-078r6: _OGC SensorThings API Part 1: Sensing_. Open Geospatial Consortium.
* OGC: OGC 17-069r4: _OGC API — Features — Part 1: Core_. Open Geospatial Consortium.
* OGC: OGC 19-086r6: _OGC API — Environmental Data Retrieval Standard_. Open Geospatial Consortium.
* OGC: OGC 20-004r1: _OGC API — Records — Part 1: Core_. Open Geospatial Consortium.
